# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'DNSwiftProject' do
  use_frameworks!

pod 'Alamofire', '~> 4.0'
pod 'SnapKit', '~> 3.0.2'
pod 'SwiftyJSON'
pod 'SwiftMessages'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
pod 'Kingfisher'
pod 'pop'
end
